[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coloredlogs>=15.0.1",
    "duckdb>=1.4.3",
    "marimo>=0.18.4",
    "numpy>=2.4.0",
    "polars[pyarrow]>=1.36.1",
    "sqlglot>=28.5.0",
    "streamlit>=1.52.2",
    "vegafusion>=2.0.3",
    "vl-convert-python>=1.9.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "ty>=0.0.8",
]
